name: Release
on:
  push:
    branches: [main]
    tags: "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update
        run: sudo apt-get update
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: sudo make install/debian
      - name: Build
        run: make build
      - name: Changelog
        run: make changelog
      - uses: ncipollo/release-action@v1
        name: Release
        with:
          bodyFile: "CHANGELOG.md"
          artifacts: "bin/lib/*.a"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
