name: Release
on:
  push:
    branches: [main]
    tags: "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update
        run: sudo apt-get update
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: sudo make install/debian
      - name: Build
        run: make build
      - name: Changelog
        run: make changelog
      - name: Version
        id: version
        shell: bash
        run: |
          RELEASE_TAG=$(git describe --tags --abbrev=0 HEAD)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)

          echo "PREVIOUS_TAG=${PREVIOUS_TAG}"
          echo "RELEASE_TAG=${RELEASE_TAG}"

          IS_WIP=$([ "${PREVIOUS_TAG}" == "${RELEASE_TAG}" ] && echo "true" || echo "false")
          if [ "${IS_WIP}" == "true" ]; then
              RELEASE_TAG=$(git describe --tags HEAD)
          fi

          echo "Tagged: ${RELEASE_TAG}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        name: Release
        with:
          bodyFile: "CHANGELOG.md"
          artifacts: "bin/lib/*.a"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.RELEASE_TAG }}
